### ISSUE TITLE
Error when running workflow

### ISSUE THREAD

**Issue by Madd0g** [exah/alfred-hotel#1]
I'm using nvm, I accidentally ran `npm install` under 5.5.0 and only then under 7.6.0, I don't really understand fully how alfy works, so maybe that's part of the cause.

Anyway, after installing in 7.6.0, I see the hotel command in alfred, but it doesn't work and prints this in debug:

```
Starting debug for 'hotel'

[ERROR: input.scriptfilter] Code 1: ~/.nvm/versions/node/v7.6.0/lib/node_modules/alfred-hotel/index.js:2
const { HOTEL_HOST = 'http://127.0.0.1:2000', TLD = 'dev' } = process.env
      ^
SyntaxError: Unexpected token {

```

It shows 7.6.0 in the path, so it probably is using the correct node version.

Any ideas?

**Comment by Madd0g** [comment]
why am I doing this at 5am.

I did a little investigation, I looked at how alfy works, changed the default node to 7.6.0, re-installed again, nothing helped.

Then I changed the const to var just for kicks and now I'm getting this error:

>JSON error: JSON text did not start with array or object and option to allow fragments not set.

It's coming after the results from hotel are fetched (so it mostly works) so maybe it's an alfy/alfred problem?

**Comment by exah** [comment]
@Madd0g Hi, thank you for reporting issue. 

I haven't tried workflow in node 7.6, will investigate tomorrow.

If you already cloned repository, could you check current node version with `node -v`, install deps with `npm install` and run `node index.js` in project folder? If node version is right, you should see json with hotel apps.

**Comment by exah** [comment]
```
[ERROR: input.scriptfilter] Code 1: ~/.nvm/versions/node/v7.6.0/lib/node_modules/alfred-hotel/index.js:2
```
This line indicates that workflow runs from `~/.nvm/versions/node/v7.6.0/lib/node_modules/` folder but not with node 7.6.0.

I think issue is that node installed via nvm isn't in your `PATH` or `PATH` is not same in Alfred and command line.

**Comment by Madd0g** [comment]
When I changed the consts to vars, I added a line that logs out the version and it is 7.6.0.

**Comment by exah** [comment]
I don't think there can be any problem with `var` / `const` if you are using [node >= 6.4](http://node.green).

So I can suggest you to:

1. Remove any `console.log` or `echo` from workflow (index.js, script filter), so it may interfere with alfred parsing JSON output
2. Open http://0.0.0.0:2000/_/servers in your browser and confirm that hotel is running
3. Send me changes you've made to workflow

**Comment by Madd0g** [comment]
Yes that url shows a JSON response from hotel.

This is the index.js after my changes, I see 7.6.0 printed from the first console.log and a normal looking array from the second console.log, the catch is not triggered.

```
console.log('grrr',process.version);
var alfy = require('alfy')
var { HOTEL_HOST = 'http://127.0.0.1:2000', TLD = 'dev' } = process.env

alfy.fetch(`${HOTEL_HOST}/_/servers`)
  .then(servers => {
    var list = Object.keys(servers).map(id => {
      var { status, cwd } = servers[id]
      var url = `http://${id}.${TLD}`
      var run = command => `{
        "alfredworkflow": {
          "arg": "${HOTEL_HOST}/_/servers/${id}",
          "variables": {
            "command": "${command}"
          }
        }
      }`

      return {
        uid: url,
        title: id,
        subtitle: status,
        arg: url,
        text: {
          copy: url,
          largetype: url
        },
        quicklookurl: status === 'running' ? url : '',
        mods: {
          alt: {
            arg: `${HOTEL_HOST}/${id}`,
            subtitle: 'open without proxy'
          },
          ctrl: {
            arg: `file://${cwd}`,
            type: 'file',
            subtitle: 'open project folder'
          },
          cmd: status === 'running'
            ? {
              arg: run('stop'),
              subtitle: 'stop'
            }
            : {}
        }
      }
    })
    console.log(list);
    alfy.output(list)
  })
  .catch(function(err) {console.log(err)})
```

**Comment by exah** [comment]
@Madd0g Have you tried to run this after you remove all `console.log` statements? 

To clarify: `console.log` and `alfy.output` both are just printing result to stdout. 
Alfred script filter is just reading stdout and trying to parse it as JSON. 

For example:

```js
console.log('grrr',process.version);
...
console.log(list);
alfy.output(list)
```

Produces not valid JSON with node version and duplicate results:

```json
v7.6.0
{
  "items": [
    {
      "uid": "http://example.dev",
      "title": "example",
      "subtitle": "stopped",
      "arg": "http://example.dev",
      "text": {
        "copy": "http://example.dev",
        "largetype": "http://example.dev"
      },
      "quicklookurl": "",
      "mods": {
        "alt": {
          "arg": "http://127.0.0.1:2000/example",
          "subtitle": "open without proxy"
        },
        "ctrl": {
          "arg": "file:///Users/USER/Developer/example",
          "type": "file",
          "subtitle": "open project folder"
        },
        "cmd": {}
      }
    }
  ]
}
{
  "items": [
    {
      "uid": "http://example.dev",
      "title": "example",
      "subtitle": "stopped",
      "arg": "http://example.dev",
      "text": {
        "copy": "http://example.dev",
        "largetype": "http://example.dev"
      },
      "quicklookurl": "",
      "mods": {
        "alt": {
          "arg": "http://127.0.0.1:2000/example",
          "subtitle": "open without proxy"
        },
        "ctrl": {
          "arg": "file:///Users/USER/Developer/example",
          "type": "file",
          "subtitle": "open project folder"
        },
        "cmd": {}
      }
    }
  ]
}
```

And thats results in parsing error:

```
JSON error: JSON text did not start with array or object and option to allow fragments not set.
```

**Comment by Madd0g** [comment]
Oh, I thought `alfy.output()` sends to alfred somehow. Sorry, should've listened last time you mentioned removing the console.log.

It does work when I remove the logging :) Woohoo, I always wanted hotel in alfred. Thanks.

I'll try the process again from scratch tomorrow to see if the const problem goes away

**Comment by exah** [comment]
Glad to hear that :)
