### ISSUE TITLE
Feature request: restart

### ISSUE THREAD

**Issue by limacohen** [exah/alfred-hotel#3]
First of all, thanks for this great, super handy workflow. Since the ability to `restart` an app from Hotel [might not be implemented](https://github.com/typicode/hotel/pull/120) by @typicode, I figured it would be cool to have it as a modifier in Alfred.

**Comment by bobmaerten** [comment]
Or a `stop`-`sleep`-`start` at least?

**Comment by exah** [comment]
Yes, that would be great feature. I'll try to implement it this week. 
But I think we out of keyboard modifiers for this action. Any ideas?

https://github.com/exah/alfred-hotel#usage
https://www.alfredapp.com/help/workflows/inputs/script-filter/json/

**Comment by exah** [comment]
Only <kbd>Fn</kbd> + <kbd>Enter</kbd> left.

**Comment by exah** [comment]
You can update with `npm i -g alfred-hotel`

**Comment by czj** [comment]
That's such a great workflow you have made, and this feature makes it even better ! Bravo :)
